### ISSUE TITLE
Useless files should be removed from the repository

### ISSUE THREAD

**Issue by RaphaelDk** [https-github-com-MarcoTeam3/VUE-FRONTEND#2]
https://github.com/https-github-com-MarcoTeam3/VUE-FRONTEND/blob/6cf06b0b5413a4a5da33cc8b29bb1b1b391b6477/src/components/NavDash.vue#L1

**Comment by inedit81** [comment]
deleted the NavDash.vue

**Comment by inedit81** [comment]
issue resolved now closing
