### ISSUE TITLE
This component should be splitted

### ISSUE THREAD

**Issue by RaphaelDk** [https-github-com-MarcoTeam3/VUE-FRONTEND#4]
https://github.com/https-github-com-MarcoTeam3/VUE-FRONTEND/blob/6cf06b0b5413a4a5da33cc8b29bb1b1b391b6477/src/views/Shop.vue#L1

**Comment by inedit81** [comment]
added carousel component

**Comment by inedit81** [comment]
added Watches component

**Comment by inedit81** [comment]
component slit in 3 closing issue
